/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PontosRouteImport } from './routes/pontos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as HemocentrosRouteImport } from './routes/hemocentros'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const PontosRoute = PontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentrosRoute = HemocentrosRouteImport.update({
  id: '/hemocentros',
  path: '/hemocentros',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/campanhas': typeof CampanhasRoute
  '/hemocentros': typeof HemocentrosRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pontos': typeof PontosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/campanhas': typeof CampanhasRoute
  '/hemocentros': typeof HemocentrosRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pontos': typeof PontosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/campanhas': typeof CampanhasRoute
  '/hemocentros': typeof HemocentrosRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pontos': typeof PontosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/campanhas'
    | '/hemocentros'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/pontos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/campanhas'
    | '/hemocentros'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/pontos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/campanhas'
    | '/hemocentros'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/pontos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CadastroRoute: typeof CadastroRoute
  CampanhasRoute: typeof CampanhasRoute
  HemocentrosRoute: typeof HemocentrosRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PontosRoute: typeof PontosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pontos': {
      id: '/pontos'
      path: '/pontos'
      fullPath: '/pontos'
      preLoaderRoute: typeof PontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentros': {
      id: '/hemocentros'
      path: '/hemocentros'
      fullPath: '/hemocentros'
      preLoaderRoute: typeof HemocentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CadastroRoute: CadastroRoute,
  CampanhasRoute: CampanhasRoute,
  HemocentrosRoute: HemocentrosRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PontosRoute: PontosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
